FROM soundbot:i3-arch

RUN yay -S --needed --noconfirm --cleanafter a2jmidid jack2 jack2-dbus qsampler linuxsampler \
    dex xss-lock i3status neovim neovim-symlinks qutebrowser numix-circle-icon-theme-git \
    pcmanfm qt6-base qt6-tools qt6-multimedia qt6-declarative gst-plugins-bad gst-libav \
    ranger sox xterm zsh zsh-completions alsa-lib alsa-plugins alsa-tools alsa-utils fmit \
    guitarix jack-keyboard njconnect catia
