cluster.name: os-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 93%
cluster.routing.allocation.disk.watermark.high: 95%

plugins.security.allow_unsafe_democertificates: true
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.authcz.admin_dn:
  - 'CN=ADMIN,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
plugins.security.nodes_dn:
  - 'CN=os00,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os01,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os02,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os03,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os04,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os05,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os06,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
  - 'CN=os07,O=SYNCOPATED,L=COLUMBUS,ST=OH,C=US'
