---
version: "3.9"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /backup/b08x/Workspace:/Workspace
      - /backup/b08x/Documents:/Documents
      - /backup/b08x/Sessions:/Sessions
      - /backup/b08x/Notebooks:/Notebooks
      - /backup/b08x/Images:/Images
      - /backup/b08x/Library:/Library
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
